name: OpenTofu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  NAT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.0

      - name: Tofu Init
        id: init
        run: tofu init
        working-directory: terraform/nat

      - name: Tofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true
        working-directory: terraform/nat

      - name: Tofu Validate
        id: validate
        run: tofu validate -no-color
        working-directory: terraform/nat